services:
  db:
    image: postgres:15-alpine
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    environment:
      POSTGRES_DB: ${DB_NAME:-osmsat_models}
      POSTGRES_USER: ${DB_USER:-osmsat}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5435}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-osmsat} -d ${DB_NAME:-osmsat_models}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
#    expose:
#      - ${PORT:-3000}
    environment:
      PORT: ${PORT:-3000}
      NODE_ENV: ${NODE_ENV:-production}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-osmsat_models}
      DB_USER: ${DB_USER:-osmsat}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DISABLE_REGISTRATION_WITHOUT_LINK: ${DISABLE_REGISTRATION_WITHOUT_LINK:-true}
    volumes:
      - ./uploads:/app/uploads
      - ./public:/app/public
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: