services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-osmsat_models}
      POSTGRES_USER: ${DB_USER:-osmsat}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-osmsat123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U osmsat"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: .
    ports:
      - "3001:3001"
    expose:
      - "8000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-osmsat_models}
      - DB_USER=${DB_USER:-osmsat}
      - DB_PASSWORD=${DB_PASSWORD:-osmsat123}
      - JWT_SECRET=${JWT_SECRET:-your-production-secret-key-here}
      - DISABLE_REGISTRATION_WITHOUT_LINK=${DISABLE_REGISTRATION_WITHOUT_LINK:-true}
    volumes:
      - ./uploads:/app/uploads
      - ./public:/app/public
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
